(executable
  (name         opam_admin_topstart)
  (public_name  opam-admin.top)
  (package      opam-admin)
  (modes        byte)
  (modules      opam_admin_topstart)
  (libraries    compiler-libs.toplevel)
  (ocamlc_flags (:standard
                (:include ../ocaml-flags-standard.sexp)
                (:include ../ocaml-flags-configure.sexp)
                (:include ../ocaml-context-flags.sexp)
                -linkall)))

(rule (with-stdout-to opam_admin_topstart.ml (echo "let _ = Topmain.main ()")))

(rule (write-file opam_installer.mli ""))

(executable
  (name        opam_installer)
  (package     opam-installer)
  (public_name opam-installer)
  (modules     opam_installer)
  (libraries   opam-format opam-core.cmdliner)
  (flags       (:standard
               (:include ../ocaml-flags-standard.sexp)
               (:include ../ocaml-flags-configure.sexp)
               (:include ../ocaml-context-flags.sexp))))
